try {
    // a=55;
    let a;
    
} catch (error) {
    console.log("error handeled "+error);
}
finally
{
    console.log("i will run always");
}
console.log("hello there");
